theme: jekyll-theme-minimal
title: Daniel Tiskin
description: linguist {and, or} philosopher</br>St Petersburg, Russia</br><img src="selfie.jpg" alt="Daniel Tiskin" title="Daniel Tiskin" style="height: 300px; float: left;">
